updated build hooks

diff --git a/hooks/post_checkout b/hooks/post_checkout
--- a/hooks/post_checkout
+++ b/hooks/post_checkout
@@ -13,41 +13,41 @@ cat "${ARCH_YAML}" > "${CONFIG_YAML}" || exit 0
 #
 while read -r line; do declare "${line}"; done < <(parse_yaml "${ARCH_YAML}")
 
-##	call any post_checkout_start() from build.conf
+##  call any post_checkout_start() from build.conf
 #
 ifFunc post_checkout_start && post_checkout_start
 
 ## parse Docker environment variables
 #
 case "${DOCKER_TAG##*-}" in
-	i*86|amd64|arm*|ppc64*|mips*|riscv64|s390x)
-		[ -z "${TARGET_TAG+set}" ] && \
-			TARGET_TAG="${DOCKER_TAG%-*}"
-		add_param "${DOCKER_TAG##*-}" 'BUILD_ARCH'
-		[ -z "${SINGLE_ARCH_BUILD+set}" ] && SINGLE_ARCH_BUILD=1
-		;;
-	*)
-		[ -z "${TARGET_TAG+set}" ] && \
-			TARGET_TAG="${DOCKER_TAG}"
-		;;
+  i*86|amd64|arm*|ppc64*|mips*|riscv64|s390x)
+    [ -z "${TARGET_TAG+set}" ] && \
+      TARGET_TAG="${DOCKER_TAG%-*}"
+    add_param "${DOCKER_TAG##*-}" 'BUILD_ARCH'
+    [ -z "${SINGLE_ARCH_BUILD+set}" ] && SINGLE_ARCH_BUILD=1
+    ;;
+  *)
+    [ -z "${TARGET_TAG+set}" ] && \
+      TARGET_TAG="${DOCKER_TAG}"
+    ;;
 esac
 
 ## parse 'latest' tag
 #
 if [ "${TARGET_TAG}" = 'latest' ]; then
-	[ -z "${SOURCE_LATEST}" ] && \
-		echo "Getting latest source tag.." && \
-		SOURCE_LATEST="$(docker_api_latest "${SOURCE_REPO}")"
+  [ -z "${SOURCE_LATEST}" ] && \
+    echo "Getting latest source tag.." && \
+    SOURCE_LATEST="$(docker_api_latest "${SOURCE_REPO}")"
 
-	[ -n "${SOURCE_LATEST}" ] && \
-		add_param "${SOURCE_LATEST}" 'SOURCE_LATEST' && \
-		TARGET_TAG="${SOURCE_LATEST}"
+  [ -n "${SOURCE_LATEST}" ] && \
+    add_param "${SOURCE_LATEST}" 'SOURCE_LATEST' && \
+    TARGET_TAG="${SOURCE_LATEST}"
 fi
 
-##	get TARGET_TAG from get_target_tag, if set in build.conf
+##  get TARGET_TAG from get_target_tag, if set in build.conf
 ifFuncSetVar TARGET_TAG get_target_tag
 
-##	get SOURCE_TAG from get_source_tag, if set in build.conf
+##  get SOURCE_TAG from get_source_tag, if set in build.conf
 ifFuncSetVar SOURCE_TAG get_source_tag
 
 [ -z ${SOURCE_TAG+set} ] && SOURCE_TAG="${TARGET_TAG}"
@@ -55,11 +55,11 @@ add_param "${SOURCE_TAG}" 'SOURCE_TAG'
 
 # set SOURCE_IMAGE, pull manifest if we're not pulling from arch-specific repos
 if [ -n "${SOURCE_REPO}" ]; then
-	SOURCE_IMAGE="${SOURCE_REPO}:${SOURCE_TAG}"
-	[ -z "${SOURCE_ARCH_PREFIX+set}" ] \
-		&& { SOURCE_MANIFEST="$(get_manifest "${SOURCE_IMAGE}")" || { echo "Exiting."; exit 1; }; }
+  SOURCE_IMAGE="${SOURCE_REPO}:${SOURCE_TAG}"
+  [ -z "${SOURCE_ARCH_PREFIX+set}" ] \
+    && { SOURCE_MANIFEST="$(get_manifest "${SOURCE_IMAGE}")" || { echo "Exiting."; exit 1; }; }
 else
-	echo "No source image, no manifest to pull."
+  echo "No source image, no manifest to pull."
 fi
 
 print_param "${DOCKER_TAG}" 'Docker tag'
@@ -70,59 +70,76 @@ add_print_param "${TARGET_TAG}" 'TARGET_TAG' 'Target tag'
 # use BUILD_ARCH if set
 #
 if [ -n "${BUILD_ARCH}" ]; then
-	build_arches="${BUILD_ARCH}"
-	for excluded_arch in ${EXCLUDED_ARCHES:-}; do
-		build_arches="$(echo "${build_arches}" | xargs -n1 | grep -vP "${excluded_arch}$" | xargs)"
-	done
+  build_arches="${BUILD_ARCH}"
+  for excluded_arch in ${EXCLUDED_ARCHES:-}; do
+    build_arches="$(echo "${build_arches}" | xargs -n1 | grep -vP "${excluded_arch}$" | xargs)"
+  done
 else
-	# configured_arches is populated from arch.yaml or INCLUDED_ARCHES
-	# and then EXCLUDED_ARCHES is applied
-	if [ ! -z "${INCLUDED_ARCHES+set}" ]; then
-		configured_arches="$(echo ${INCLUDED_ARCHES} | sort -u | xargs)"
-	else
-		configured_arches="$(sed -En 's/(^\w*):\s*$/\1/p' "${ARCH_YAML}" | sort -u | xargs)"
-	fi
-	print_param "${configured_arches}" 'Configured arches'
+  # configured_arches is populated from arch.yaml or INCLUDED_ARCHES
+  # and then EXCLUDED_ARCHES is applied
+  if [ ! -z "${INCLUDED_ARCHES+set}" ]; then
+    configured_arches="$(echo ${INCLUDED_ARCHES} | sort -u | xargs)"
+  else
+    configured_arches="$(sed -En 's/(^\w*):\s*$/\1/p' "${ARCH_YAML}" | sort -u | xargs)"
+  fi
+  print_param "${configured_arches}" 'Configured arches'
 
-	if [ ! -z "${EXCLUDED_ARCHES+set}" ]; then
-		print_param "${EXCLUDED_ARCHES}" 'Excluded arches'
-		for excluded in ${EXCLUDED_ARCHES}; do
-			configured_arches="$(echo "${configured_arches}" | xargs -n1 | grep -v "^${excluded}$" | sort -u | xargs)"
-		done
-	fi
+  if [ ! -z "${EXCLUDED_ARCHES+set}" ]; then
+    print_param "${EXCLUDED_ARCHES}" 'Excluded arches'
+    for excluded in ${EXCLUDED_ARCHES}; do
+      configured_arches="$(echo "${configured_arches}" | xargs -n1 | grep -v "^${excluded}$" | sort -u | xargs)"
+    done
+  fi
 
-	# find available architectures in source repo(s)
-	#
-	# if nothing is cached and SOURCE_ARCH_PREFIX is set, pull manifest from each
-	# of the '<arch>/' repos (e.g. arm32v7/<image>, s390x/<image>, etc..)
-	#
-	# otherwise use the multi-arch manifest we pulled earlier, SOURCE_MANIFEST
-	#
-	if [ -n "${SOURCE_ARCHES:-}" ]; then
-		source_arches="${SOURCE_ARCHES}"
-	elif [ ! -z "${SOURCE_ARCH_PREFIX+set}" ]; then
-		unset source_arches
-		for arch in ${configured_arches}; do
-			arch_prefix_var="${arch}_QEMU_PREFIX"
-			import_image="${!arch_prefix_var:-_}/${SOURCE_REPO}:${SOURCE_TAG}"
-			[ -s "$(get_manifest "${import_image}")" ] && source_arches+="${arch} "
-		done
-	else
-		print_param "${SOURCE_MANIFEST}" 'Source manifest'
-		source_arches="$(sed -n -e 'N;s/.*Arch:\s*\(\w*\)\n.*Variant:\s*\(\w*\)/\1\2/p;D;' "${SOURCE_MANIFEST}" \
-			| sed -e 's/[^\w]*386/i386/' | sort -u | xargs)"
-	fi
+  # find available architectures in source repo(s)
+  #
+  # if nothing is cached and SOURCE_ARCH_PREFIX is set, pull manifest from each
+  # of the '<arch>/' repos (e.g. arm32v7/<image>, s390x/<image>, etc..)
+  #
+  # otherwise use the multi-arch manifest we pulled earlier, SOURCE_MANIFEST
+  #
+  unset source_arches
 
-	# default arch if manifest-tool doesn't return anything useful
-	[ -z "${source_arches}" ] && source_arches='amd64'
+  if [ -n "${SOURCE_ARCHES:-}" ]; then
+    source_arches="${SOURCE_ARCHES}"
+  elif [ ! -z "${SOURCE_ARCH_PREFIX+set}" ]; then
+    for arch in ${configured_arches}; do
+      arch_prefix_var="${arch}_QEMU_PREFIX"
+      import_image="${!arch_prefix_var:-_}/${SOURCE_REPO}:${SOURCE_TAG}"
+      [ -s "$(get_manifest "${import_image}")" ] && source_arches+="${arch} "
+    done
+  else
+    print_param "${SOURCE_MANIFEST}" 'Source manifest'
 
-	print_param "${source_arches}" 'Source arches'
+    # this fails if there is no "Variant"
+    # source_arches="$(sed -n -e 'N;s/.*Arch:\s*\(\w*\)\n.*Variant:\s*\(\w*\)/\1\2/p;D;' "${SOURCE_MANIFEST}" \
+    #   | sed -e 's/[^\w]*386/i386/' | sort -u | xargs)"
 
-	# build_arches is the intersection of configtured_arches and source_arches
-	build_arches="$(comm -12 \
-		<(echo "${configured_arches}" | xargs -n1 | LC_ALL=C sort) \
-		<(echo "${source_arches}" | xargs -n1 | LC_ALL=C sort) \
-		| xargs)"
+    arch_count="$(grep -oP '^\[[0-9]*\]' "${SOURCE_MANIFEST}" | tail -1 | grep -o '[0-9]*')"
+
+    [ ! -z "${DEBUG}" ] && >&2 echo 'processing manifest:'
+
+    if [ ! -n "${arch_count}" ]; then
+      source_arches="$(get_arch_from_manifest "${SOURCE_MANIFEST}")"
+    else
+      n=0; until [ "${n}" == "${arch_count}" ]; do
+        n=$((n+1))
+        source_arches+="$(get_arch_from_manifest "${SOURCE_MANIFEST}" "${n}")"
+      done
+      source_arches="$(echo ${source_arches} | xargs -n1 | sed -e 's/[^\w]*386/i386/' | sort -u | xargs)"
+    fi
+  fi
+
+  # default arch if manifest-tool doesn't return anything useful
+  [ -z "${source_arches}" ] && source_arches='amd64'
+
+  print_param "${source_arches}" 'Source arches'
+
+  # build_arches is the intersection of configtured_arches and source_arches
+  build_arches="$(comm -12 \
+    <(echo "${configured_arches}" | xargs -n1 | LC_ALL=C sort) \
+    <(echo "${source_arches}" | xargs -n1 | LC_ALL=C sort) \
+    | xargs)"
 fi
 add_print_param "${build_arches}" 'build_arches' 'Build arches'
 
@@ -130,49 +147,49 @@ add_print_param "${build_arches}" 'build_arches' 'Build arches'
 #
 platforms=''
 for arch in ${build_arches}; do
-	manifest_platform="${arch}_MANIFEST_PLATFORM"
-	[ -n "${!manifest_platform}" ] \
-		&& platform_string="${arch}_MANIFEST_PLATFORM" \
-		|| platform_string="${arch}_PLATFORM"
+  manifest_platform="${arch}_MANIFEST_PLATFORM"
+  [ -n "${!manifest_platform}" ] \
+    && platform_string="${arch}_MANIFEST_PLATFORM" \
+    || platform_string="${arch}_PLATFORM"
   platforms="${platforms},${!platform_string}"
 done
 add_print_param "${platforms:1}" 'platforms' 'Platforms'
 
 [ -z "${platforms}" ] \
-	&& echo "No platforms found. Exiting." \
-	&& exit 1
+  && echo "No platforms found. Exiting." \
+  && exit 1
 
 add_print_param "${SOURCE_IMAGE}" 'SOURCE_IMAGE' 'Source image'
 
-##	read keys from arch.yaml
+##  read keys from arch.yaml
 #
 arch_yaml_keys="$(sed -En 's|^[[:space:]][[:space:]](.*):.*|\1|p' ${ARCH_YAML} | sort -u | xargs)"
 # available_keys="$(comm -12 <(printf '%s\n' ${arch_yaml_keys} \
-	# | LC_ALL=C sort) <(printf '%s\n' ${ARCH_KEYS} | LC_ALL=C sort) | xargs)"
+  # | LC_ALL=C sort) <(printf '%s\n' ${ARCH_KEYS} | LC_ALL=C sort) | xargs)"
 # add_param "${available_keys}" 'available_keys'
 add_param "${arch_yaml_keys}" 'available_keys'
 
 # expect PYTHON_WHEELS to be a list of wheels each set as such:
 #
-#		<module_name>(-<ssl_library)([>|=]=<module_version)
+#    <module_name>(-<ssl_library)([>|=]=<module_version)
 #
 if [ -n "${PYTHON_WHEELS+set}" ]; then
-	wheel_tags=''
-	for wheel in ${PYTHON_WHEELS}; do
-		wheel_version="$(py_required_version "${wheel}")" \
-			|| continue
-		wheel_name="${wheel%%[=<>]*}"
-		wheel_tags="${wheel_name%-}${wheel_version} ${wheel_tags}"
-	done
-	add_print_param "${wheel_tags}" 'WHEEL_TAGS' 'Python wheels'
+  wheel_tags=''
+  for wheel in ${PYTHON_WHEELS}; do
+    wheel_version="$(py_required_version "${wheel}")" \
+      || continue
+    wheel_name="${wheel%%[=<>]*}"
+    wheel_tags="${wheel_name%-}${wheel_version} ${wheel_tags}"
+  done
+  add_print_param "${wheel_tags}" 'WHEEL_TAGS' 'Python wheels'
 fi
 
-##	call any post_checkout_end() from build.conf
+##  call any post_checkout_end() from build.conf
 #
 ifFuncExec post_checkout_end
 
 for param in $(echo "${!CHECKOUT_DISPLAY[@]}" | xargs -n1 | sort); do
-	[ -n "${!param}" ] && print_param "${!param}" "${CHECKOUT_DISPLAY[${param}]}"
+  [ -n "${!param}" ] && print_param "${!param}" "${CHECKOUT_DISPLAY[${param}]}"
 done
 
 echo
diff --git a/hooks/post_push b/hooks/post_push
--- a/hooks/post_push
+++ b/hooks/post_push
@@ -4,92 +4,95 @@
 
 # push_platforms <target_tag> <base_tag>
 push_platforms () {
-	[ -n "${RATE_LIMITED+set}" ] && return
+  [ -n "${RATE_LIMITED+set}" ] && return
 
-	[ -n "${platforms:-}" ] || { echo "No platforms to push."; return 0; }
+  [ -n "${platforms:-}" ] || { echo "No platforms to push."; return 0; }
 
-	# remove duplicates
-	clean_platforms=''
-	for platform in $(echo ${platforms} | xargs -d',' -n1); do
-		echo "${clean_platforms}" | xargs -d',' | grep -q "${platform}" \
-			|| clean_platforms+=",${platform}"
-	done
-	platforms="${clean_platforms:1}"
+  # remove duplicates
+  clean_platforms=''
+  for platform in $(echo ${platforms} | xargs -d',' -n1); do
+    echo "${clean_platforms}" | xargs -d',' | grep -q "${platform}" \
+      || clean_platforms+=",${platform}"
+  done
+  platforms="${clean_platforms:1}"
 
-	local base_tag
-	[ -n "${2}" ] && base_tag="${2}" || base_tag="${1}"
+  local base_tag
+  [ -n "${2}" ] && base_tag="${2}" || base_tag="${1}"
 
-	# allow for empty basetag and ARCHVARIANT-only template
-	[ -n "${base_tag}" ] && base_tag="${base_tag}-"
+  # allow for empty basetag and ARCHVARIANT-only template
+  [ -n "${base_tag}" ] && base_tag="${base_tag}-"
 
-	local target_tag
-	[ -n "${1}" ] && target_tag="${1}" || target_tag='latest'
+  local target_tag
+  [ -n "${1}" ] && target_tag="${1}" || target_tag='latest'
 
-	IFS=' ' read -r -a manifest_cmd <<< "$(get_manifest_tool)"
-	manifest_cmd+=(push from-args --platforms "${platforms}" --template "${DOCKER_REPO}:${base_tag}ARCHVARIANT" --target "${DOCKER_REPO}:${target_tag}")
+  IFS=' ' read -r -a manifest_cmd <<< "$(get_manifest_tool)"
+  manifest_cmd+=(push from-args --platforms "${platforms}" --template "${DOCKER_REPO}:${base_tag}ARCHVARIANT" --target "${DOCKER_REPO}:${target_tag}")
 
-	[ ! -z "${DEBUG+set}" ] \
-		&& pretty_manifest_cmd="$(echo "${manifest_cmd[*]}" | sed -r -e "s/(--)/\\\ \n\t\1/g")" \
-		&& echo '--- manifest command ---' && printf '%s\n' "${pretty_manifest_cmd}"
+  [ ! -z "${DEBUG+set}" ] \
+    && pretty_manifest_cmd="$(echo "${manifest_cmd[*]}" | sed -r -e "s/(--)/\\\ \n\t\1/g")" \
+    && echo '--- manifest command ---' && printf '%s\n' "${pretty_manifest_cmd}"
 
-	printf '%-20s ' "${target_tag}"
+  printf '%-20s ' "${target_tag}"
 
-	[ -n "${NOOP+set}" ] && echo '[NOOP]' && return 0
-	[ -n "${NO_PUSH+set}" ] && echo '[NO_PUSH]' && return 0
-#	{ "${manifest_cmd[@]}" | grep -i Digest | cut -d' ' -f2; } || { echo 'Could not push manifest.'; return 1; }
-#	"${manifest_cmd[@]}" || { echo 'Could not push manifest.'; return 1; }
-	local error
-	error="$("${manifest_cmd[@]}" 2>&1)";
+  [ -n "${NOOP+set}" ] && echo '[NOOP]' && return 0
+  [ -n "${NO_PUSH+set}" ] && echo '[NO_PUSH]' && return 0
 
-	if [ -n "${error}" ]; then
-		case ${error} in
-			*toomanyrequests*)
-				printf 'rate limited!\n\nSkipping remaining post_push..\n'
-				RATE_LIMITED='true'
-				POST_PUSH_SKIPPED="${DOCKER_TAG}"
-				return
-				;;
-			*)
-				printf 'unknown error:\n%s\n' "${error}"
-				exit 1
-				;;
-		esac
-		return 1
-	fi
-	echo
+#  { "${manifest_cmd[@]}" | grep -i Digest | cut -d' ' -f2; } || { echo 'Could not push manifest.'; return 1; }
+#  "${manifest_cmd[@]}" || { echo 'Could not push manifest.'; return 1; }
+
+  local error
+  { error="$("${manifest_cmd[@]}" 3>&2 2>&1 1>&3)"; } 2>&1 # | cut -d' ' -f2
+
+  if [ -n "${error}" ]; then
+    case ${error} in
+      *toomanyrequests*)
+        printf 'rate limited!\n\nSkipping remaining post_push..\n'
+        RATE_LIMITED='true'
+        POST_PUSH_SKIPPED="${DOCKER_TAG}"
+        return
+        ;;
+      *)
+        printf 'unknown error:\n%s\n' "${error}"
+        exit 1
+        ;;
+    esac
+    return 1
+  fi
 }
 
 if [ -n "${SINGLE_ARCH_BUILD}" ]; then
-	echo "Single arch build, not pushing manifests."
+  echo "Single arch build, not pushing manifests."
 elif [ ! -z "${SKIP_BUILD+set}" ]; then
-	echo "Skipping."
+  echo "Skipping."
 elif [ -n "${NO_MANIFEST+set}" ]; then
-	echo "NO_MANIFEST is set, skipping post_push."
+  echo "NO_MANIFEST is set, skipping post_push."
 elif [ -n "${NO_POST_PUSH+set}" ]; then
-	echo "NO_POST_PUSH is set, skipping post_push."
+  echo "NO_POST_PUSH is set, skipping post_push."
 elif [ -n "${RATE_LIMITED+set}" ]; then
-	echo "skip in post_push"
-	POST_PUSH_SKIPPED="${POST_PUSH_SKIPPED} ${DOCKER_TAG}"
+  echo "skip in post_push"
+  POST_PUSH_SKIPPED="${POST_PUSH_SKIPPED} ${DOCKER_TAG}"
+elif [ ! -z "${BUILD_MULTIARCH+set}" ]; then
+  echo "BUILD_MULTIARCH is set, skipping post push."
 else
-	manifest_tags=()
+  manifest_tags=()
 
-	ifFunc get_manifest_tags && IFS=' ' read -r -a manifest_tags <<< "$(get_manifest_tags)"
-	manifest_tags+=("${TARGET_TAG}")
+  ifFunc get_manifest_tags && IFS=' ' read -r -a manifest_tags <<< "$(get_manifest_tags)"
+  manifest_tags+=("${TARGET_TAG}")
 
-	[ "${DOCKER_TAG}" = "latest" ] && manifest_tags+=('latest')
+  [ "${DOCKER_TAG}" = "latest" ] && manifest_tags+=('latest')
 
-	IFS=' ' read -r -a manifest_tags <<< "$(echo "${manifest_tags[*]}" | xargs -n1 | sort -u | xargs)"
+  IFS=' ' read -r -a manifest_tags <<< "$(echo "${manifest_tags[*]}" | xargs -n1 | sort -u | xargs)"
 
-	echo "--- post_push (${manifest_tags[*]}) ---"
+  echo "--- post_push (${manifest_tags[*]}) ---"
 
-	if (( ${#manifest_tags[@]} )); then
-		for tag in "${manifest_tags[@]}"; do push_platforms "${tag}" "${TARGET_TAG}";	done
-	else
-#		echo 'No manifest tags to push.'
-		push_platforms
-	fi
+  if (( ${#manifest_tags[@]} )); then
+    for tag in "${manifest_tags[@]}"; do push_platforms "${tag}" "${TARGET_TAG}";  done
+  else
+#    echo 'No manifest tags to push.'
+    push_platforms
+  fi
 fi
 
-##	call any post_push_end() from build.conf
+##  call any post_push_end() from build.conf
 #
 ifFuncExec post_push_end
