module version bump; multi-arch docker

diff --git a/hooks/post_push b/hooks/post_push
--- a/hooks/post_push
+++ b/hooks/post_push
@@ -1,28 +1,43 @@
 #!/usr/bin/env bash
 
-## get the repo and tag strings
-#
-image_repo=${IMAGE_NAME%:*}
-image_tag=${IMAGE_NAME#*:}
+. hooks/env
 
-## generate and apply extra tags
-#
-tags=()
+[ -n "${BUILD_ARCH+set}" ]	&& echo "Single arch build, not pushing manifests." && exit 0
 
-if [ "${image_tag}" = "binary" ]; then
-        tags+=('latest')
-fi
+# push_platforms <target_tag> <base_tag>
+push_platforms () {
+	[ -n "${platforms}" ] || { echo "No platforms to push."; return 0; }
 
-## push the tags
-#
-push_tags()     {
-        for tag in ${tags[@]}; do
-                echo '---'
-                echo "Adding tag: ${image_repo}:${tag}"
-                echo '---'
-                docker tag $IMAGE_NAME ${image_repo}:${tag}
-                docker push ${image_repo}:${tag}
-        done
+	local base_tag
+	[ -n "${2}" ] && base_tag="${2}" || base_tag="${1}"
+
+	IFS=' ' read -r -a manifest_cmd <<< "$(get_manifest_tool)"
+	manifest_cmd+=(push from-args --platforms "${platforms}" --template "${DOCKER_REPO}:${base_tag}-ARCHVARIANT" --target "${DOCKER_REPO}:${1}")
+
+#	pretty_manifest_cmd="$(echo "${manifest_cmd[*]}" | sed -r -e "s/(--)/\\\ \n\t\1/g")"
+#	echo '--- manifest command ---' && printf '%s\n' "${pretty_manifest_cmd}"
+
+	printf '%-20s ' "${1}:"
+
+	[[ -n "${NOOP+set}" || -n "${NOPUSH+set}" ]] && echo '[NOOP]' && return 0
+	"${manifest_cmd[@]}" || { echo "*** Could not push manifest."; return 1; }
+	echo
 }
 
-push_tags
+manifest_tags=()
+
+ifFunc get_manifest_tags && IFS=' ' read -r -a manifest_tags <<< "$(get_manifest_tags)"
+
+manifest_tags+=("${TARGET_TAG}")
+
+[ "${DOCKER_TAG}" = "latest" ] && manifest_tags+=('latest')
+
+IFS=' ' read -r -a manifest_tags <<< "$(echo "${manifest_tags[*]}" | xargs -n1 | sort -u | xargs)"
+
+echo "--- post_push (${manifest_tags[*]}) ---"
+
+if (( ${#manifest_tags[@]} )); then
+	for tag in "${manifest_tags[@]}"; do push_platforms "${tag}" "${TARGET_TAG}";	done
+else
+	echo 'No manifest tags to push.'
+fi
